name: Build AvaloniaUI (Win & Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: 8.0.x
  PROJECT_PATH: SwarmCloneLauncher.csproj
  LAUNCH_DIR: Launch

jobs:
  build:
    name: ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-latest
          - rid: linux-x64
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up UTF-8 encoding (Windows)
        if: runner.os == 'Windows'
        run: chcp 65001

      - name: Set up UTF-8 encoding (Linux)
        if: runner.os == 'Linux'
        run: echo "LANG=C.UTF-8" >> $GITHUB_ENV
        
      - name: Build C++ launch (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -S "${{ env.LAUNCH_DIR }}" -B "${{ env.LAUNCH_DIR }}/build" -DCMAKE_BUILD_TYPE=Release
          cmake --build "${{ env.LAUNCH_DIR }}/build" --config Release
          Copy-Item "${{ env.LAUNCH_DIR }}/build/Release/launch.exe" -Destination "launch.exe"

      - name: Build C++ launch (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake -S "${{ env.LAUNCH_DIR }}" -B "${{ env.LAUNCH_DIR }}/build" -DCMAKE_BUILD_TYPE=Release
          cmake --build "${{ env.LAUNCH_DIR }}/build" --config Release
          cp "${{ env.LAUNCH_DIR }}/build/launch" ./launch

      - name: Restore NuGet packages
        run: dotnet restore "${{ env.PROJECT_PATH }}" -r ${{ matrix.rid }}

      - name: Publish .NET project (Native AOT)
        run: |
          dotnet publish "${{ env.PROJECT_PATH }}" `
            -c Release `
            -r ${{ matrix.rid }} `
            -p:DebugSymbols=false `
            -p:DebugType=None `
            -p:EnableCompressionInSingleFile=true `
            --self-contained true `
            -o "launcher"

      - name: Check if executable exists (Linux)
        if: runner.os == 'Linux'
        run: |
          ls -la launcher/
          if [ -f "launcher/SwarmCloneLauncher" ]; then
            echo "Executable exists"
            ldd launcher/SwarmCloneLauncher || true
          else
            echo "Executable not found"
            exit 1
          fi

      - name: Create final package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path final
          Copy-Item launch.exe -Destination final/
          
          New-Item -ItemType Directory -Force -Path final/launcher
          Copy-Item "launcher/*" -Recurse -Destination final/launcher/
          
          cd final
          7z a "../${{ matrix.rid }}.zip" ./*

      - name: Create final package (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p final
          cp launch final/
          
          mkdir -p final/launcher
          cp -r launcher/* final/launcher/
          
          chmod +x final/launcher/SwarmCloneLauncher
          
          echo "Final file size:"
          ls -lh final/launcher/SwarmCloneLauncher
          
          cd final
          zip -r "../${{ matrix.rid }}.zip" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}
          path: ${{ matrix.rid }}.zip