# .github/workflows/build.yml
name: Build AvaloniaUI (Win & Linux)

on:
  push:
    branches: [ main ]      # 每次 push 到 main 都会触发
  pull_request:
    branches: [ main ]      # PR 也触发

env:
  DOTNET_VERSION: 8.0.x
  PROJECT_PATH: SwarmCloneLauncher.csproj   # 换成实际路径

jobs:
  build:
    name: ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-latest
          - rid: linux-x64
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Publish
        run: >
          dotnet publish "${{ env.PROJECT_PATH }}"
          -c Release
          -r ${{ matrix.rid }}
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -o "publish/${{ matrix.rid }}"

      - name: Zip artifacts
        run: |
          cd "publish/${{ matrix.rid }}"
          zip -r "../${{ matrix.rid }}.zip" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}
          path: publish/${{ matrix.rid }}.zip