name: Build AvaloniaUI (Win & Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: 8.0.x
  PROJECT_PATH: SwarmCloneLauncher.csproj
  LAUNCH_DIR: Launch

jobs:
  build:
    name: ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-latest
          - rid: linux-x64
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build C++ launch (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -S "${{ env.LAUNCH_DIR }}" -B "${{ env.LAUNCH_DIR }}/build" -DCMAKE_BUILD_TYPE=Release
          cmake --build "${{ env.LAUNCH_DIR }}/build" --config Release
          Copy-Item "${{ env.LAUNCH_DIR }}/build/Release/launch.exe" -Destination "launch.exe"

      - name: Build C++ launch (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake -S "${{ env.LAUNCH_DIR }}" -B "${{ env.LAUNCH_DIR }}/build" -DCMAKE_BUILD_TYPE=Release
          cmake --build "${{ env.LAUNCH_DIR }}/build" --config Release
          cp "${{ env.LAUNCH_DIR }}/build/launch" ./launch

      - name: Restore .NET project
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Publish .NET project
        run: >
          dotnet publish "${{ env.PROJECT_PATH }}"
          -c Release
          -r ${{ matrix.rid }}
          --self-contained true
          -p:PublishSingleFile=true
          -p:PublishReadyToRun=true
          -p:DebugSymbols=false
          -o "launcher"

      - name: Create final package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path final
          Copy-Item launch.exe -Destination final/
          Copy-Item launcher -Recurse -Destination final/
          Compress-Archive -Path final/* -DestinationPath "${{ matrix.rid }}.zip"

      - name: Create final package (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p final
          cp launch final/
          cp -r launcher final/
          cd final
          zip -r "../${{ matrix.rid }}.zip" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}
          path: ${{ matrix.rid }}.zip