name: Build AvaloniaUI (Win & Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: 8.0.x
  PROJECT_PATH: SwarmCloneLauncher.csproj
  LAUNCH_DIR: Launch

jobs:
  build:
    name: ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-latest
          - rid: linux-x64
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up UTF-8 encoding (Windows)
        if: runner.os == 'Windows'
        run: chcp 65001

      - name: Set up UTF-8 encoding (Linux)
        if: runner.os == 'Linux'
        run: echo "LANG=C.UTF-8" >> $GITHUB_ENV
        
      - name: Build C++ launch (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -S "${{ env.LAUNCH_DIR }}" -B "${{ env.LAUNCH_DIR }}/build" -DCMAKE_BUILD_TYPE=Release
          cmake --build "${{ env.LAUNCH_DIR }}/build" --config Release
          Copy-Item "${{ env.LAUNCH_DIR }}/build/Release/launch.exe" -Destination "launch.exe"

      - name: Build C++ launch (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake -S "${{ env.LAUNCH_DIR }}" -B "${{ env.LAUNCH_DIR }}/build" -DCMAKE_BUILD_TYPE=Release
          cmake --build "${{ env.LAUNCH_DIR }}/build" --config Release
          cp "${{ env.LAUNCH_DIR }}/build/launch" ./launch

      - name: Restore NuGet packages
        run: dotnet restore "${{ env.PROJECT_PATH }}" -r ${{ matrix.rid }}

      - name: Publish .NET project as single file
        run: >
          dotnet publish "${{ env.PROJECT_PATH }}"
          -c Release
          -r ${{ matrix.rid }}
          --self-contained true
          /p:PublishSingleFile=true
          /p:DebugType=None
          /p:DebugSymbols=false
          /p:EnableCompressionInSingleFile=true
          /p:IncludeNativeLibrariesForSelfExtract=true
          /p:IncludeAllContentForSelfExtract=true
          /p:CopyOutputSymbolsToPublishDirectory=false
          /p:UseAppHost=true
          /p:SelfContained=true
          /p:RuntimeIdentifier=${{ matrix.rid }}
          -o "launcher"

      - name: Check file size
        run: |
          echo "Checking file sizes in launcher directory:"
          if [ "${{ matrix.rid }}" = "win-x64" ]; then
            find launcher -name "*.exe" -exec ls -lh {} \;
          else
            find launcher -name "SwarmCloneLauncher" -exec ls -lh {} \;
          fi

      - name: Create final package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path final
          Copy-Item launch.exe -Destination final/
          
          New-Item -ItemType Directory -Force -Path final/launcher
          Copy-Item "launcher/*" -Recurse -Destination final/launcher/
          
          Compress-Archive -Path final/* -DestinationPath "${{ matrix.rid }}.zip"

      - name: Create final package (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p final
          cp launch final/
          
          mkdir -p final/launcher
          cp -r launcher/* final/launcher/
          
          chmod +x final/launcher/SwarmCloneLauncher
          
          echo "Final file size:"
          ls -lh final/launcher/SwarmCloneLauncher
          
          cd final
          zip -r "../${{ matrix.rid }}.zip" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}
          path: ${{ matrix.rid }}.zip